#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/xlutil_py
  
  rm -rf build/* tmp/* 
  
  pySloc -L py  -X cover -X htmlcov -X dist -v $@ \
      src/extsrc src/xlutil \
      tests \
      setup.py
else
  echo "DEV_BASE is not defined"
fi
