#!/usr/bin/env bash

if [ ! -z "${DEV_BASE// }" ]
then
  cd $DEV_BASE/py/xlutil_py
  
  rm -rf build/* tmp/* 
  
  pySloc -L py  -X cover -X htmlcov -X dist -v $@ src/xlutil tests/testContext.py tests/testNamespace.py tests/testTimestamp.py tests/test_pop_count.py setup.py
else
  echo "DEV_BASE is not defined"
fi
