[meta]
version = "0.1.0"

[project]
name = "xlutil_py"
package = "xlutil"
main_lang = "py"
version = "0.1.8"
version_date = "2017-12-21"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2017"
description = "utilid layer for xlattice_py"
dev_status = "pre_alpha"
license = "mit"
relpath = "py/xlutil_py"
state = "shared"
url = "https://jddixon.github.io/xlutil_py"

[py]
packages = [ "xlutil",]
package_dir = [ "src",]
test_dir = [ "tests",]
py_modules = []
scripts = []
ext_modules = []
distshare = [ "rnglib",]
env_vars = [ "TZ",]
requirements = [ "context", "setuptools",]
test_requirements = []
