projConfig.toml for xlutil_py

[meta]
    version = '0.1.0'

[project]
    name = 'xlutil_py'  # distro name
    package = 'xlutil_py'  # internal name
    proj_dir = '/home/jdd/dev/py/xlutil_py'
    main_lang = 'py'
    version = '0.1.7'
    version_date = '2017-10-09'
    author = 'Jim Dixon'
    author_email = 'jddixon@gmail.com'
    copyright = '2017'
    description = 'utilid layer for xlattice_py'
    dev_status = 'pre_alpha'
    license = 'mit'
    state = 'shared'
    url = 'https://jddixon.github.io/xlutil_py'

[py]
    packages=['xlutil']
    package_dir = ['src']
    test_dir = ['tests']
    py_modules=[]
    scripts=[]
    ext_modules=[]

    # sdReq output
    distshare=['rnglib']
    env_vars=['TZ']
    requirements=['context', 'setuptools']
    test_requirements=[]
